### ISSUE TITLE
pip unable to install

### ISSUE THREAD

**Issue by Sanmejie** [UltimatePancake/pyjavaproperties#2]
![image](https://user-images.githubusercontent.com/40269911/88169582-c4d48980-cc4e-11ea-92bc-ba122ea4042e.png)

**Comment by Sanmejie** [comment]
win 10 64
python 3.7

**Comment by pgaetani** [comment]
Added some encoding on commit 3ce5ea1 , let me know if that fixes it @Sanmejie .

**Comment by Sanmejie** [comment]
![image](https://user-images.githubusercontent.com/40269911/89406143-506e1000-d74f-11ea-9ad7-38d76515ade2.png)
It is all right now.
