### ISSUE TITLE
Cannot  change after execution

### ISSUE THREAD

**Issue by Sanmejie** [UltimatePancake/pyjavaproperties#3]
```
# -*- coding:utf-8 -*-
from pyjavaproperties import Properties
p = Properties()
p.load(open('test2.properties'))
p['python.Version'] = 'test=5.4.0'
p.store(open('test2.properties','w'))
```

test2.properties info
python.Version=3.6.4
requests.Version=2.23.0
pytest.Version=5.4.0
environment=development_environment

![image](https://user-images.githubusercontent.com/40269911/89407717-dab77380-d751-11ea-95a7-5123268212a3.png)

**Comment by Sanmejie** [comment]
![image](https://user-images.githubusercontent.com/40269911/89408273-b5773500-d752-11ea-8963-6d4db29e25f9.png)
The test2.properties file is empty after an error occurs

**Comment by Sanmejie** [comment]
issue was settled ，But there's one small problem,Is Chinese not supported in the current document? 
![image](https://user-images.githubusercontent.com/40269911/89410334-20763b00-d756-11ea-8c37-325f1908feac.png)
![image](https://user-images.githubusercontent.com/40269911/89410680-c45fe680-d756-11ea-8e4d-afb3095069c9.png)
![image](https://user-images.githubusercontent.com/40269911/89410714-d2ae0280-d756-11ea-877d-64beca294872.png)
![image](https://user-images.githubusercontent.com/40269911/89410633-ac886280-d756-11ea-8a5c-433c64dab26b.png)

**Comment by Sanmejie** [comment]
Hope to get attention, thank you @UltimatePancake

**Comment by pgaetani** [comment]
That bit seems to have been down to the strftime formatting, I've removed the timestamp default output and set it as a variable, also removed the %Z bit which was giving that weird encoding.

`timestamp` and `timeformat` params can be set now to get around that.
